spring:
  application:
     name: cloudbasedproject

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB

aws:
  region: eu-west-1
  s3:
    bucket: cloudbasedproject-bucket


server:
  port: 2020

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
