spring:
  application:
     name: cloudbasedproject

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cloudbasedproject}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 20MB

aws:
  region: eu-west-1
  s3:
    bucket: cloudbasedproject-bucket


server:
  port: 2020

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
