name: Deploy ECS App via CodeDeploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download imagedefinitions.json
        uses: actions/download-artifact@v4
        with:
          name: image-defs

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload artifacts to S3
        run: |
          aws s3 cp appspec.yaml s3://your-s3-bucket/
          aws s3 cp imagedefinitions.json s3://your-s3-bucket/

      - name: Create deployment
        run: |
          aws deploy create-deployment \
            --application-name cloudbasedproject-codedeploy \
            --deployment-group-name cloudbasedproject-deployment-group \
            --s3-location bucket=your-s3-bucket,bundleType=YAML,key=appspec.yaml \
            --file-exists-behavior OVERWRITE \
            --description "Auto deployment from GitHub"
